sudo: required

language: java

services:
  - docker

before_install:
- docker pull hrchu/mogilefs-all-in-one:version-1.1.5
- docker run -e DOMAIN_NAME=testdomain -e CLASS_NAMES="testclass1 testclass2" -t -d -p 7001:7001 -p 7500:7500 --name maio hrchu/mogilefs-all-in-one:version-1.1.5
- timeout 60 nc -zv 127.0.0.1 7001

script:
- mvn verify

after_failure:
  - cat target/surefire-reports/*.txt

cache:
  directories:
  - $HOME/.m2
